### ISSUE TITLE
Sugestões de modificações no driver si1145_microbit.py

### ISSUE THREAD

**Issue by thiagofe** [neliogodoi/MicroPython-BME280#1]
Olá Nélio, gostaria de sugerir modificações no driver si1145_microbit.py:

- Adicionar "from time import sleep" no driver si1145_microbit.py: https://github.com/neliogodoi/MicroPython-SI1145/blob/master/si1145_microbit.py

- Adiconar um exemplo para micro:bit (Testing): https://github.com/neliogodoi/MicroPython-SI1145

**Comment by neliogodoi** [comment]
Olá Tiago! Obrigado pela sugestão!
Como este espaço não é do driver em questão... estou mudando para lá este conteúdo!

Obrigado!
